kind: Template
apiVersion: v1
metadata:
  name: deploymentconfig-ejb3-remoting
  annotations:
    openshift.io/display-name: "EJB3 remoting with deploymentconfig setup"
    description: "How the EJB3 remoting works with deploymentconfig"
    iconClass: "icon-eap"
    tags: "eap,javaee,java,jboss"
  message: "A new JBoss EJB3 remoting example with DeploymentConfig was deployed"

parameters:
  - name: CLIENT_APPLICATION
    displayName: "Client application name"
    value: "tx-client"
    required: true
  - name: CLIENT_CONTEXT_DIR
    displayName: Context Directory
    description: Path within Git project to build; empty for root project directory.
    value: 'tx-client'
    required: false
  - name: SERVER_APPLICATION
    displayName: "Server application name"
    value: "tx-server"
    required: true
  - name: SERVER_CONTEXT_DIR
    displayName: Context Directory
    description: Path within Git project to build; empty for root project directory.
    value: 'tx-server'
    required: false
  - name: KUBE_PING_NAMESPACE
    displayName: Namespace for Kube ping protocol
    description: What is namespace for Kube ping protocol, usually the project name of the deployments.
    value: 'myproject'
    required: false
  - name: MEMORY_LIMIT
    displayName: "Container memory limit"
    value: "1Gi"
    required: false
  - name: VOLUME_CAPACITY
    displayName: "Capacity of the shared volume of the jboss eap stuff"
    value: "1Gi"
    required: false
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: Git source URI for application
    value: https://github.com/ochaloup/openshift-tx.git
    required: true
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Git branch/tag reference
    value: 'eap71-statefulset-call-error'
    required: false
  - name: CUSTOM_INSTALL_DIRECTORIES
    displayName: Custom install directories (see documentation).
    description: Additional directories from which to install.
    value: extensions/*
    required: false
  - name: MAVEN_MIRROR_URL
    displayName: Maven mirror URL
    description: Maven mirror to use for S2I builds
    value: ''
    required: false
  - name: MAVEN_ARGS_APPEND
    displayName: Maven Additional Arguments
    description: Maven additional arguments to use for S2I builds
    value: ''
    required: false
  - name: ARTIFACT_DIR
    description: List of directories from which archives will be copied into the deployment folder. If unspecified, all archives in /target will be copied.
    value: ''
    required: false
  - name: IMAGE_STREAM_NAMESPACE
    displayName: ImageStream Namespace
    description: Default is without any namespace. Middleware goes usually to openshift namespace. It is where EAP image is searched at.
    value: 'openshift'
    required: false
  - name: GITHUB_WEBHOOK_SECRET
    displayName: Github Webhook Secret
    description: GitHub trigger secret
    from: "[a-zA-Z0-9]{8}"
    generate: expression
    required: true
  - name: GENERIC_WEBHOOK_SECRET
    displayName: Generic Webhook Secret
    description: Generic build trigger secret
    from: "[a-zA-Z0-9]{8}"
    generate: expression
    required: true
  - name: SCRIPT_DEBUG
    description: Running OpenShift EAP scripts with set -x
    value: "false"
    required: false

objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${CLIENT_APPLICATION}"
      labels:
        application: "${CLIENT_APPLICATION}"
      annotations:
        description: "Service for client"
    spec:
      clusterIP: None
      ports:
        - name: eap-http
          port: 8080
          targetPort: 8080
      selector:
        application: "${CLIENT_APPLICATION}"

  - kind: Service
    apiVersion: v1
    metadata:
      name: "${SERVER_APPLICATION}"
      labels:
        application: "${SERVER_APPLICATION}"
      annotations:
        description: "Service for server"
    spec:
      clusterIP: None
      ports:
        - name: eap-http
          port: 8080
          targetPort: 8080
      selector:
        application: "${SERVER_APPLICATION}"

  - kind: Route
    apiVersion: v1
    id: "${CLIENT_APPLICATION}-http"
    metadata:
      name: "${CLIENT_APPLICATION}"
      labels:
        application: "${CLIENT_APPLICATION}"
      annotations:
        description: Route for the tx-client application http service.
    spec:
      to:
        name: "${CLIENT_APPLICATION}"


  - kind: DeploymentConfig
    apiVersion: v1
      metadata:
        name: "${CLIENT_APPLICATION}"
        labels:
          application: "${CLIENT_APPLICATION}"
    spec:
      strategy:
        type: Recreate
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${CLIENT_APPLICATION}"
            from:
              kind: ImageStreamTag
              name: "${CLIENT_APPLICATION}:latest"
        - type: ConfigChange
          replicas: 1
          selector:
            application: "${CLIENT_APPLICATION}"
          template:
            metadata:
              name: "${CLIENT_APPLICATION}"
              labels:
                application: "${CLIENT_APPLICATION}"
            spec:
              terminationGracePeriodSeconds: 75
              containers:
                - name: "${CLIENT_APPLICATION}"
                  image: "${CLIENT_APPLICATION}"
                  imagePullPolicy: Always
                  resources:
                    limits:
                      memory: "${MEMORY_LIMIT}"
                  livenessProbe:
                    exec:
                      command:
                        - "/bin/bash"
                        - "-c"
                        - "/opt/eap/bin/livenessProbe.sh"
                    initialDelaySeconds: 60
                  readinessProbe:
                    exec:
                      command:
                        - "/bin/bash"
                        - "-c"
                        - "/opt/eap/bin/readinessProbe.sh"
                  ports:
                    - name: jolokia
                      containerPort: 8778
                      protocol: TCP
                    - name: http
                      containerPort: 8080
                      protocol: TCP
                    - name: ping
                      containerPort: 8888
                      protocol: TCP
                  env:
                    - name: OPENSHIFT_KUBE_PING_NAMESPACE
                      value: "${KUBE_PING_NAMESPACE}"
                    - name: OPENSHIFT_KUBE_PING_LABELS
                      value: "application=${CLIENT_APPLICATION}"
                    - name: JAVA_OPTS_APPEND
                      value: "-Dtx.server.host=${SERVER_APPLICATION} -Djboss.default.multicast.address=230.0.0.5" # consider removing multicast.address parameter
                    - name: SCRIPT_DEBUG
                      value: "${SCRIPT_DEBUG}"

  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${CLIENT_APPLICATION}"
      labels:
        application: "${CLIENT_APPLICATION}"

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${CLIENT_APPLICATION}"
      labels:
        application: "${CLIENT_APPLICATION}"
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${CLIENT_CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          env:
          - name: MAVEN_MIRROR_URL
            value: "${MAVEN_MIRROR_URL}"
          - name: MAVEN_ARGS_APPEND
            value: "${MAVEN_ARGS_APPEND}"
          - name: ARTIFACT_DIR
            value: "${ARTIFACT_DIR}"
          forcePull: true
          incremental: true
          from:
            kind: ImageStreamTag
            namespace: "${IMAGE_STREAM_NAMESPACE}"
            name: "eap-image-stream:latest"
      output:
        to:
          kind: ImageStreamTag
          name: "${CLIENT_APPLICATION}:latest"
      triggers:
      - type: GitHub
        github:
          secret: "${GITHUB_WEBHOOK_SECRET}"
      - type: Generic
        generic:
          secret: "${GENERIC_WEBHOOK_SECRET}"
      - type: ImageChange
        imageChange: {}
      - type: ConfigChange

  - kind: DeploymentConfig
    apiVersion: v1
      metadata:
        name: "${SERVER_APPLICATION}"
        labels:
          application: "${SERVER_APPLICATION}"
    spec:
      strategy:
        type: Recreate
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${SERVER_APPLICATION}"
            from:
              kind: ImageStreamTag
              name: "${SERVER_APPLICATION}:latest"
        - type: ConfigChange
          replicas: 1
          selector:
            application: "${SERVER_APPLICATION}"
          template:
            metadata:
              name: "${SERVER_APPLICATION}"
              labels:
                application: "${SERVER_APPLICATION}"
            spec:
              terminationGracePeriodSeconds: 75
              containers:
                - name: "${SERVER_APPLICATION}"
                  image: "${SERVER_APPLICATION}"
                  imagePullPolicy: Always
                  resources:
                    limits:
                      memory: "${MEMORY_LIMIT}"
                  livenessProbe:
                    exec:
                      command:
                        - "/bin/bash"
                        - "-c"
                        - "/opt/eap/bin/livenessProbe.sh"
                    initialDelaySeconds: 60
                  readinessProbe:
                    exec:
                      command:
                        - "/bin/bash"
                        - "-c"
                        - "/opt/eap/bin/readinessProbe.sh"
                  ports:
                    - name: jolokia
                      containerPort: 8778
                      protocol: TCP
                    - name: http
                      containerPort: 8080
                      protocol: TCP
                    - name: ping
                      containerPort: 8888
                      protocol: TCP
                  env:
                    - name: OPENSHIFT_KUBE_PING_NAMESPACE
                      value: "${KUBE_PING_NAMESPACE}"
                    - name: OPENSHIFT_KUBE_PING_LABELS
                      value: "application=${SERVER_APPLICATION}"
                    - name: JAVA_OPTS_APPEND
                      value: "-Djboss.default.multicast.address=230.0.0.5" # consider removing multicast.address parameter
                    - name: SCRIPT_DEBUG
                      value: "${SCRIPT_DEBUG}"

  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${SERVER_APPLICATION}"
      labels:
        application: "${SERVER_APPLICATION}"

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${SERVER_APPLICATION}"
      labels:
        application: "${SERVER_APPLICATION}"
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${SERVER_CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          env:
          - name: MAVEN_MIRROR_URL
            value: "${MAVEN_MIRROR_URL}"
          - name: MAVEN_ARGS_APPEND
            value: "${MAVEN_ARGS_APPEND}"
          - name: ARTIFACT_DIR
            value: "${ARTIFACT_DIR}"
          forcePull: true
          incremental: true
          from:
            kind: ImageStreamTag
            namespace: "${IMAGE_STREAM_NAMESPACE}"
            name: "eap-image-stream:latest"
      output:
        to:
          kind: ImageStreamTag
          name: "${SERVER_APPLICATION}:latest"
      triggers:
      - type: GitHub
        github:
          secret: "${GITHUB_WEBHOOK_SECRET}"
      - type: Generic
        generic:
          secret: "${GENERIC_WEBHOOK_SECRET}"
      - type: ImageChange
        imageChange: {}
      - type: ConfigChange


  # https://docs.openshift.com/container-platform/latest/dev_guide/managing_images.html#insecure-registries
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: eap-image-stream
      annotations:
        openshift.io/display-name: JBossEAP
    spec:
      tags:
        - name: 'latest'
          from:
            kind: DockerImage
            name: 'registry.access.redhat.com/jboss-eap-7/eap71-openshift:latest'


  # allow the default service account to list pods
  - apiVersion: v1
    kind: Role
    metadata:
      name: pods-listing
    rules:
    - apiGroups: null
      attributeRestrictions: null
      resources: ["pods"]
      verbs: ["list"]
  - apiVersion: v1
    kind: RoleBinding
    metadata:
      name: claim-pod-listing-to-default
      annotations:
        description: "Role binding for the default service account"
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: ${IMAGE_STREAM_NAMESPACE} # TODO: this is probably needed but could be configured as different evn var
    roleRef:
      kind: Role
      name: pods-listing
      namespace: ${IMAGE_STREAM_NAMESPACE}

